language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./main.py
  - python -m compileall ./cogs
  - python -m compileall ./utilities
cache: pip
notifications:
  email: false
dist: xenial
os: linux
